import type { Metadata } from 'next';
import { League_Gothic } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from 'sonner';

const leagueGothic = League_Gothic({
  variable: '--font-league-gothic',
  subsets: ['latin'],
  weight: '400',
});

const tradeGothicNext = localFont({
  src: [
    {
      path: '../../fonts/trade-gothic-next.woff2',
      weight: '400',
    },
  ],
  variable: '--font-trade-gothic-next',
});

const bimboFinetip = localFont({
  src: [
    {
      path: '../../fonts/bimbo-finetip.woff2',
      weight: '400',
    },
  ],
  variable: '--font-bimbo-finetip',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${leagueGothic.variable} ${bimboFinetip.variable} ${tradeGothicNext.variable} antialiased`}
      >
        {children}
        <Toaster position='bottom-center' />
      </body>
    </html>
  );
}
